### ISSUE TITLE
Documentation Titles Word-break oddly due to Codefund adverts

### ISSUE THREAD

**Issue by GeorgeWL** [mobxjs/mobx#2027]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:
* [x] Documentation improvement. Please don't open an issue but create a PR instead!
* [x] Are you willing to (attempt) a PR yourself?

Please tick the appropriate boxes. Feel free to remove the _other_ sections.

**Please be sure to close your issues promptly.**

![image](https://user-images.githubusercontent.com/5931248/60424537-750cc580-9be8-11e9-87e8-7bc42e7983c7.png)
Page Headers get broken by the codefund div, causing a weird word-break half way through a title.

A quick fix I tried in inspect was:
```css
.book .book-body .page-wrapper .page-inner section.normal h1, .book .book-body .page-wrapper .page-inner section.normal h2, .book .book-body .page-wrapper .page-inner section.normal h3, .book .book-body .page-wrapper .page-inner section.normal h4, .book .book-body .page-wrapper .page-inner section.normal h5, .book .book-body .page-wrapper .page-inner section.normal h6 {
  width:100%;
  display:flex;
  justify-content:flex-start;
}
```
I've yet to test this though to see if it has any knock-on effects.
